### ISSUE TITLE
Unable to Toggle Voxel Preview

### ISSUE THREAD

**Issue by LeonardoBevilacqua** [GoodAI/space-engineers-ai-spaceship-generator#4]
*Issue type:* [ bug ]

*Severity:* [ medium ]

**Describe the issue**
An exception is throw when trying to toggle voxel preview. All buttons become disabled.

**To Reproduce**
1. Open the AI.Spaceship.Generator.v1.0.0.exe
2. Wait initialize
3. click "Toggle Voxel Preview"
4. Exception:
```
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
  File "pcgsepy\guis\main_webapp\webapp.py", line 3612, in general_callback
  File "pcgsepy\guis\main_webapp\webapp.py", line 2626, in __toggle_voxelization
IndexError: list index out of range
ERROR:pcgsepy.guis.main_webapp.webapp:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
  File "pcgsepy\guis\main_webapp\webapp.py", line 3612, in general_callback
  File "pcgsepy\guis\main_webapp\webapp.py", line 2626, in __toggle_voxelization
IndexError: list index out of range
```

**Expected behavior**
All buttons become disabled, can't use the application.

**Screenshots**
If applicable, please add screenshots to help explain your problem, they tremendously help understanding the issue.

**Desktop (please complete the following information):**
 - OS: [Windows 11]
 - Browser: [Chrome, Brave]
 - .exe file name: AI.Spaceship.Generator.v1.0.0.exe

**Comment by gallorob** [comment]
It looks like you tried toggling the voxel preview without selecting a spaceship first, I'll get that fixed right away.
Thank you for finding and reporting this bug!

**Comment by gallorob** [comment]
@martinpoliak-goodai please include commit https://github.com/arayabrain/space-engineers-ai-spaceship-generator/commit/4305d970a5caa1e1eca6acfc38ba067622688412 in the repo and in the next release, it solves this issue.

@LeonardoBevilacqua I'm going to close the issue for now; please wait for either the merge or the new executable release to test it again.

**Comment by gallorob** [comment]
@LeonardoBevilacqua I've merged the commit to this repository, if you can run from source you can test it again, otherwise please wait for the next release.
