### ISSUE TITLE
Error upon file upload

### ISSUE THREAD

**Issue by Zemogiter** [GoodAI/space-engineers-ai-spaceship-generator#6]
*Issue type:* bug 

*Severity:*  high (application-breaking) 

**Describe the issue**
Uploading files causes this error:
```
Serving webapp on http://127.0.0.1:8051/...
Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
  File "pcgsepy\guis\ships_comparator\webapp.py", line 552, in general_callback
  File "pcgsepy\guis\ships_comparator\webapp.py", line 552, in <listcomp>
  File "pcgsepy\guis\ships_comparator\webapp.py", line 184, in parse_contents
ValueError: too many values to unpack (expected 3)
ERROR:pcgsepy.guis.ships_comparator.webapp:Exception on /_dash-update-component [POST]
Traceback (most recent call last):
  File "flask\app.py", line 2525, in wsgi_app
  File "flask\app.py", line 1822, in full_dispatch_request
  File "flask\app.py", line 1820, in full_dispatch_request
  File "flask\app.py", line 1796, in dispatch_request
  File "dash\dash.py", line 1261, in dispatch
  File "dash\_callback.py", line 440, in add_context
  File "pcgsepy\guis\ships_comparator\webapp.py", line 552, in general_callback
  File "pcgsepy\guis\ships_comparator\webapp.py", line 552, in <listcomp>
  File "pcgsepy\guis\ships_comparator\webapp.py", line 184, in parse_contents
ValueError: too many values to unpack (expected 3)
```
Dosen't matter if its one file or all 4 at once.
**To Reproduce**
1. Launch `Spaceships Comparator (no Pytorch)_*date*.exe` (I coppied the missing line from https://github.com/arayabrain/space-engineers-ai-spaceship-generator/commit/25d0300c22a5075e89f0564e1deb2cf56fd4ae0c , ran the .py file and launched the exe file in `dist` subfolder)
2. Click on 'Drag and Drop or Select Files' button
3. Select files

**Expected behavior**
Images of selected ships showing up under their names (Spaceship A/B/C/D).

**Screenshots**
No applicable screenshot.

**Log file**
No log file found but here's output from compiler:
```
C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\venv\Scripts\python.exe "C:/Program Files/JetBrains/PyCharm Community Edition 2021.3.2/plugins/python-ce/helpers/pydev/pydevd.py" --multiprocess --qt-support=auto --client 127.0.0.1 --port 58350 --file C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\build_comparator.py 
Connected to pydev debugger (build 222.4345.23)
962 INFO: PyInstaller: 5.6.1
962 INFO: Python: 3.10.2
972 INFO: Platform: Windows-10-10.0.19044-SP0
973 INFO: wrote C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\Spaceships Comparator (no Pytorch)_20221028.spec
977 INFO: UPX is not available.
977 INFO: Removing temporary files and cleaning cache in C:\Users\Jonasz\AppData\Local\pyinstaller
1051 INFO: Extending PYTHONPATH with paths
['C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\user-study']
2199 INFO: checking Analysis
2199 INFO: Building Analysis because Analysis-00.toc is non existent
2199 INFO: Initializing module dependency graph...
2202 INFO: Caching module graph hooks...
2225 WARNING: Several hooks defined for module 'numpy'. Please take care they do not conflict.
2235 INFO: Analyzing base_library.zip ...
5308 INFO: Loading module hook 'hook-encodings.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
7569 INFO: Loading module hook 'hook-pickle.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
11283 INFO: Loading module hook 'hook-heapq.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
12710 INFO: Caching module dependency graph...
13309 INFO: running Analysis Analysis-00.toc
13350 INFO: Adding Microsoft.Windows.Common-Controls to dependent assemblies of final executable
  required by C:\Users\Jonasz\AppData\Local\Programs\Python\Python310\python.exe
13459 INFO: Analyzing C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\comparator_webapp_launcher.py
13633 INFO: Loading module hook 'hook-platform.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
14460 INFO: Loading module hook 'hook-dash.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
14816 INFO: Loading module hook 'hook-plotly.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
53740 INFO: Processing pre-find module path hook distutils from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-distutils.py'.
54474 INFO: Loading module hook 'hook-distutils.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
54960 INFO: Loading module hook 'hook-PIL.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
55113 INFO: Loading module hook 'hook-PIL.Image.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
56409 INFO: Loading module hook 'hook-pycparser.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
57295 INFO: Loading module hook 'hook-distutils.util.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
57367 INFO: Loading module hook 'hook-sysconfig.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
57922 INFO: Loading module hook 'hook-setuptools.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
61672 INFO: Loading module hook 'hook-pkg_resources.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
64909 INFO: Loading module hook 'hook-xml.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
66615 INFO: Loading module hook 'hook-multiprocessing.util.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
68061 INFO: Loading module hook 'hook-PIL.ImageFilter.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
69104 INFO: Loading module hook 'hook-numpy.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\Lib\\site-packages\\numpy\\_pyinstaller'...
70022 INFO: Loading module hook 'hook-numpy._pytesttester.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
70736 INFO: Loading module hook 'hook-difflib.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
74056 INFO: Loading module hook 'hook-pandas.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
77213 INFO: Loading module hook 'hook-pytz.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
79070 INFO: Processing pre-safe import module hook six.moves from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-six.moves.py'.
81456 INFO: Loading module hook 'hook-scipy.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
82138 INFO: Loading module hook 'hook-matplotlib.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
83124 INFO: Loading module hook 'hook-packaging.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
83413 INFO: Processing pre-safe import module hook gi from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-gi.py'.
84895 INFO: Loading module hook 'hook-jinja2.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
87068 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
91273 INFO: Loading module hook 'hook-certifi.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
91397 INFO: Loading module hook 'hook-scipy.linalg.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
92039 INFO: Loading module hook 'hook-scipy.sparse.csgraph.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
94571 INFO: Loading module hook 'hook-scipy.spatial.transform.rotation.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
100216 INFO: Loading module hook 'hook-pandas.io.formats.style.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
105561 INFO: Loading module hook 'hook-pandas.plotting.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
109067 INFO: Loading module hook 'hook-xml.etree.cElementTree.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
109131 INFO: Loading module hook 'hook-xml.dom.domreg.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
110360 INFO: Loading module hook 'hook-sqlite3.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
113811 INFO: Loading module hook 'hook-kaleido.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
115077 INFO: Processing pre-safe import module hook urllib3.packages.six.moves from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_safe_import_module\\hook-urllib3.packages.six.moves.py'.
117942 INFO: Loading module hook 'hook-patsy.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
121302 INFO: Loading module hook 'hook-statsmodels.tsa.statespace.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
145199 INFO: Loading module hook 'hook-flask_compress.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
145291 INFO: Loading module hook 'hook-dash_bootstrap_components.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\stdhooks'...
146399 INFO: Processing pre-find module path hook pyi_splash from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\pre_find_module_path\\hook-pyi_splash.py'.
146401 INFO: Adding pyi_splash module to application dependencies.
146412 INFO: Processing module hooks...
296947 INFO: Loading module hook 'hook-matplotlib.backends.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
296948 INFO: Matplotlib backend selection method: automatic discovery of used backends
297920 INFO: Trying determine the default backend as first importable candidate from the list: ['Qt5Agg', 'Gtk3Agg', 'TkAgg', 'WxAgg']
302087 INFO: Selected matplotlib backends: ['TkAgg']
304767 INFO: Loading module hook 'hook-PIL.SpiderImagePlugin.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
305020 INFO: Processing pre-safe import module hook win32com from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\_pyinstaller_hooks_contrib\\hooks\\pre_safe_import_module\\hook-win32com.py'.
307976 INFO: Loading module hook 'hook-scipy.special._ellip_harm_2.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
307977 INFO: Loading module hook 'hook-scipy.special._ufuncs.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
307979 INFO: Loading module hook 'hook-scipy.stats._stats.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
308078 INFO: Loading module hook 'hook-setuptools.msvc.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
312048 INFO: Loading module hook 'hook-_tkinter.py' from 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks'...
315319 INFO: checking Tree
315319 INFO: Building Tree because Tree-00.toc is non existent
315319 INFO: Building Tree Tree-00.toc
315592 INFO: checking Tree
315592 INFO: Building Tree because Tree-01.toc is non existent
315592 INFO: Building Tree Tree-01.toc
316967 INFO: checking Tree
316967 INFO: Building Tree because Tree-02.toc is non existent
316967 INFO: Building Tree Tree-02.toc
322354 INFO: Looking for ctypes DLLs
322574 INFO: Analyzing run-time hooks ...
322877 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_inspect.py'
322879 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_subprocess.py'
322882 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgutil.py'
322887 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_multiprocessing.py'
322893 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_setuptools.py'
322895 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_pkgres.py'
322906 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth__tkinter.py'
322908 INFO: Including run-time hook 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\PyInstaller\\hooks\\rthooks\\pyi_rth_mplconfig.py'
323884 INFO: Looking for dynamic libraries
C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\venv\lib\site-packages\PyInstaller\building\build_main.py:173: UserWarning: The numpy.array_api submodule is still experimental. See NEP 47.
  __import__(package)
6189 INFO: Extra DLL search directories (AddDllDirectory): ['C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\numpy\\.libs', 'C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\lib\\site-packages\\scipy.libs']
6189 INFO: Extra DLL search directories (PATH): ['C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\venv\\Scripts', 'c:\\devkitPro\\msys2\\usr\\bin', 'C:\\Program Files (x86)\\Common Files\\Oracle\\Java\\javapath', 'C:\\Windows\\system32', 'C:\\Windows', 'C:\\Windows\\System32\\Wbem', 'C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\', 'C:\\Windows\\System32\\OpenSSH\\', 'C:\\ProgramData\\chocolatey\\bin', 'C:\\Program Files (x86)\\GtkSharp\\2.12\\bin', 'C:\\Program Files (x86)\\WinMerge', 'C:\\Program Files (x86)\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Intel\\Intel(R) Management Engine Components\\DAL', 'C:\\Program Files\\Microsoft SQL Server\\150\\Tools\\Binn\\', 'C:\\Program Files\\Microsoft SQL Server\\Client SDK\\ODBC\\170\\Tools\\Binn\\', 'C:\\Program Files\\Git\\cmd', 'C:\\Program Files (x86)\\FAHClient', 'C:\\Program Files\\dotnet\\', 'C:\\Users\\Jonasz\\AppData\\Local\\Programs\\Python\\Python310\\Scripts\\', 'C:\\Users\\Jonasz\\AppData\\Local\\Programs\\Python\\Python310\\', 'C:\\Users\\Jonasz\\AppData\\Local\\Microsoft\\WindowsApps', 'C:\\Users\\Jonasz\\AppData\\Local\\GitHubDesktop\\bin', 'C:\\Program Files\\JetBrains\\PyCharm Community Edition 2021.3.2\\bin', 'C:\\Users\\Jonasz\\.dotnet\\tools', 'C:\\Program Files\\JetBrains\\IntelliJ IDEA 2022.2\\bin', 'C:\\Users\\Jonasz\\AppData\\Local\\Programs\\Microsoft VS Code\\bin']
337096 INFO: Looking for eggs
337096 INFO: Using Python library C:\Users\Jonasz\AppData\Local\Programs\Python\Python310\python310.dll
337096 INFO: Found binding redirects: 
[]
337336 INFO: Warnings written to C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\build\Spaceships Comparator (no Pytorch)_20221028\warn-Spaceships Comparator (no Pytorch)_20221028.txt
341617 INFO: Graph cross-reference written to C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\build\Spaceships Comparator (no Pytorch)_20221028\xref-Spaceships Comparator (no Pytorch)_20221028.html
343517 INFO: Appending 'datas' from .spec
343592 INFO: checking PYZ
343592 INFO: Building PYZ because PYZ-00.toc is non existent
343592 INFO: Building PYZ (ZlibArchive) C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\build\Spaceships Comparator (no Pytorch)_20221028\PYZ-00.pyz
360667 INFO: Building PYZ (ZlibArchive) C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\build\Spaceships Comparator (no Pytorch)_20221028\PYZ-00.pyz completed successfully.
362124 INFO: Collect tcl/tk binaries for the splash screen
364487 INFO: checking Tree
364487 INFO: Building Tree because Tree-03.toc is non existent
364487 INFO: Building Tree Tree-03.toc
364695 INFO: checking Tree
364695 INFO: Building Tree because Tree-04.toc is non existent
364695 INFO: Building Tree Tree-04.toc
365919 INFO: checking Tree
365919 INFO: Building Tree because Tree-05.toc is non existent
365919 INFO: Building Tree Tree-05.toc
367136 INFO: checking Splash
367136 INFO: Building Splash because Splash-00.toc is non existent
367137 INFO: Building Splash C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\build\Spaceships Comparator (no Pytorch)_20221028\Splash-00.res
367156 INFO: checking PKG
367156 INFO: Building PKG because PKG-00.toc is non existent
367156 INFO: Building PKG (CArchive) Spaceships Comparator (no Pytorch)_20221028.pkg
411997 INFO: Building PKG (CArchive) Spaceships Comparator (no Pytorch)_20221028.pkg completed successfully.
412692 INFO: Bootloader C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\venv\lib\site-packages\PyInstaller\bootloader\Windows-64bit\run.exe
412692 INFO: checking EXE
412692 INFO: Building EXE because EXE-00.toc is non existent
412692 INFO: Building EXE from EXE-00.toc
412705 INFO: Copying bootloader EXE to C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\dist\Spaceships Comparator (no Pytorch)_20221028.exe.notanexecutable
412817 INFO: Copying icon to EXE
412818 INFO: Copying icons from ['C:\\Users\\Jonasz\\Documents\\GitHub\\space-engineers-ai-spaceship-generator\\user-study\\assets\\favicon.ico']
412914 INFO: Writing RT_GROUP_ICON 0 resource with 20 bytes
412914 INFO: Writing RT_ICON 1 resource with 4264 bytes
412917 INFO: Copying 0 resources to EXE
412918 INFO: Embedding manifest in EXE
412921 INFO: Updating manifest in C:\Users\Jonasz\Documents\GitHub\space-engineers-ai-spaceship-generator\user-study\dist\Spaceships Comparator (no Pytorch)_20221028.exe.notanexecutable
413022 INFO: Updating resource type 24 name 1 language 0
413026 INFO: Appending PKG archive to EXE
413208 INFO: Fixing EXE headers
414917 INFO: Building EXE from EXE-00.toc completed successfully.

Process finished with exit code 0
```
**Desktop (please complete the following information):**
 - OS: Windows 10 22H1
 - Browser: Chrome 107.0.5304.88
 - .exe file name: Spaceships Comparator (no Pytorch)_20221028.exe

**Additional context**
`build_comparator.py` after the change:
[build_comparator.zip](https://github.com/GoodAI/space-engineers-ai-spaceship-generator/files/9887610/build_comparator.zip)

**Comment by gallorob** [comment]
Hi @Zemogiter, I tried reproducing this behaviour but am unable to obtain the same error. 

Could you try uploading the spaceships located in `user-study\dummy_results` (named `spaceship_{ID}_exp{N}? If you are able to upload those but can't upload yours, please upload the files here and I'll take a look!

**Comment by Zemogiter** [comment]
Nvm, I tried to upload the .zip files with the blueprints. The app does not accept that input - maybe a pop-up that tells the users if they try to do the same, to instead extract those files.

**Comment by gallorob** [comment]
@Zemogiter that's a good suggestion! Will implement it and close the issue once updated.

**Comment by gallorob** [comment]
Added in https://github.com/GoodAI/space-engineers-ai-spaceship-generator/commit/d058ef3079aa83dfb83fe6b5e5ba01a93c92b2e9

Will be included in the next release; thank you for the suggestion @Zemogiter 😃 

![image](https://user-images.githubusercontent.com/32876132/198909426-1941636f-5f2b-453c-af99-c649491aa5f2.png)
